# Generated by Django 5.1.1 on 2024-09-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0003_alter_document_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="title",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
