# Generated by Django 5.1.1 on 2024-09-08 14:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0004_alter_document_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="owner",
        ),
    ]
