# Generated by Django 5.1.1 on 2024-09-09 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0007_remove_document_file_size"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="editable_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="editable_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="is_draft",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="document",
            name="land_owner_agreed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="document",
            name="land_seller_agreed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="documents/"),
        ),
    ]
