# Generated by Django 5.1.1 on 2024-09-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0008_document_editable_by_document_is_draft_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="terms_conditions",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="is_draft",
            field=models.BooleanField(default=False),
        ),
    ]
