# Generated by Django 5.1.1 on 2024-09-11 11:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0010_remove_document_terms_conditions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="editable_by",
        ),
        migrations.RemoveField(
            model_name="document",
            name="is_draft",
        ),
        migrations.RemoveField(
            model_name="document",
            name="land_owner_agreed",
        ),
        migrations.RemoveField(
            model_name="document",
            name="land_seller_agreed",
        ),
    ]
