# Generated by Django 5.1.1 on 2024-09-11 14:12

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "documents",
            "0011_remove_document_editable_by_remove_document_is_draft_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="documents/",
                validators=[documents.models.validate_file_type],
            ),
        ),
    ]
